name: create-release
on:
  push:
    branches:
      - master # Creating a tag dispatches a push event, so we have to filter for master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: "git clone https://github.com/OverflowCat/logseq-pdf-nav.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bundle @logseq/libs dependency
        run: |
          ls
          cd logseq-pdf-nav
          echo "<script>" > lsplugin.user.min.js
          curl "https://cdn.jsdelivr.net/npm/@logseq/libs/dist/lsplugin.user.min.js" >> lsplugin.user.min.js
          echo "</script>" >> lsplugin.user.min.js
          sed '8d' -i 'index.html'
          sed -e "7r lsplugin.user.min.js" -i 'index.html'
      - name: Create and upload archive
        run: |
          cd logseq-pdf-nav
          version=$(jq -r '.version' package.json)
          name=$(jq -r '.name' package.json)
          echo "Now packaging version $version…"
          zip ${name}-v${version}.zip ./*.*
          gh release create v${version} ${name}-v${version}.zip package.json
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
